#load balancing via https://geek-cookbook.funkypenguin.co.nz/ha-docker-swarm/keepalived/
---
- hosts: swarmnodes

  tasks: 
  - name: loading kernel module ip_vs
    shell: >
      echo "modprobe ip_vs" >> /etc/modules
      modprobe ip_vs

  - name: Starting Keepalived containers with floating Cluster IP 192.168.178.100
    shell: >
      docker run -d --name keepalived --restart=always \
      --cap-add=NET_ADMIN --cap-add=NET_BROADCAST --cap-add=NET_RAW --net=host \
      -e KEEPALIVED_UNICAST_PEERS="#PYTHON2BASH:['192.168.178.97', '192.168.178.98', '192.168.178.99]" \
      -e KEEPALIVED_VIRTUAL_IPS=192.168.178.100 \
      osixia/keepalived:2.0.20
    run_once: true
