---
- hosts: swarmnodes
  become: yes

  tasks:
  - name: Create Gluster Pool
    gluster.gluster.gluster_peer:
      state: present
      nodes: "{{ item }}"
    with_items: 
        - "{{ groups['swarmnodes'] }}"     
    run_once: true    

  - name: Create Path for Gluster
    file:
      path: /gluster
      state: directory

