---
- hosts: swarmnodes
  become: yes

  tasks:
  - name: Create Gluster Pool
    gluster.gluster.gluster_peer:
      state: present
      nodes:
        - swarm-node1
        - swarm-node2
        - swarm-node3
    run_once: true    

  - name: Create Path for Gluster
    file:
      path: /gluster
      state: directory

  