---
- hosts: swarmnodes
  become: yes

  tasks:
  - name: Create Gluster Pool
    gluster.gluster.gluster_peer:
      state: present
      nodes: "{{ item }}"
    with_items: 
        - "{{ groups['swarmnodes'] }}"     
    run_once: true    

  - name: Create Path for Gluster
    file:
      path: /gluster
      state: directory

  - name: Create Mount Path for Gluster
    file:
      path: /mount
      state: directory

  - name: Create Gluster Brick
    gluster.gluster.gluster_volume:
      state: present
      name: swarmfs
      bricks: /gluster/swarm
      cluster: "{{ groups['swarmnodes'] }}"
      replicas: 3
      force: true
    run_once: true
    tags:
      - betterbrick

  - name: start volume
    gluster.gluster.gluster_volume:
      state: started
      name: swarmfs

  - name: Mount GlusterFS on Reboot via fstab
    shell: >
      echo 'localhost:/swarmfs /mount glusterfs defaults,_netdev,backupvolfile-server=localhost 0 0' >> /etc/fstab

  - name: Mount GlusterFS
    shell: >
      mount.glusterfs localhost:/swarmfs /mount
    tags:
      - mount